services:
  - type: worker
    name: werewolf-noir
    env: python
    rootDir: werewolf_bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
